<a href="https://colab.research.google.com/github/stephanyresque/Ciencia-de-dados/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#criando uma matriz unidimensional
mt = np.array([12,34,56,34])
print(mt)
print(type(mt))

[12 34 56 34]
<class 'numpy.ndarray'>


In [ ]:
#criando uma array de tipo específico
mtfloat = np.array([1,2,3], dtype = np.float64) #cria uma array de tipo float de 64 bits
print(mtfloat)
mtint = np.array([1,2,3], dtype = np.int32) #cria uma array de tipo int de 32 bits
print(mtint)

[1. 2. 3.]
[1 2 3]


In [ ]:
#podemos mudar um tipo de uma array
mtold = np.array([2.4, 4.999, 5,7, 1.2])
print(mtold)
mtnew = mtold.astype(np.int32)
print(mtnew)

[2.4   4.999 5.    7.    1.2  ]
[2 4 5 7 1]


In [ ]:
arr = np.array([1,2,3])
arr_new = arr.astype(float)
print(arr_new)

[1. 2. 3.]


In [ ]:
#criando uma matriz bidimensional
mt7 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(mt7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
vazio = np.empty([3,2], dtype = int) #crio uma matriz de 3 linhas e 2 colunas que não será inicializada e terá valores aleatórios
print(vazio)
print("\n")
zero = np.zeros([3,2]) #crio uma matriz de 3 linhas e 2 colunas que será inicializada com zeros
print(zero)
print("\n")
one = np.ones([3,2]) #crio uma matriz de 3 linhas e 2 colunas que será inicializada com uns
print(one)
print("\n")
diagonal = np.eye(3) #crio uma matriz quadrada que será inicializada com a diagonal 1 e o resto 0
print(diagonal)
print("\n")

[[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




In [ ]:
#cria valores aleatórios entre 0 e 1
ale = np.random.random(5) #tbm posso ([x,y]) -> fazer uma matriz
print(ale)
print("\n")
#valores aleatório distribuição normal contendo negativos
ale2 = np.random.randn(5)
print(ale2)
print("\n")
ale_mat = 5 * (np.random.random((3,2)))
print(ale_mat)


[0.75092695 0.61078309 0.25570033 0.14683904 0.77535555]


[ 2.22448446  1.07929203  0.88726643  0.33995505 -0.27909053]


[[2.89060514 0.36949468]
 [4.7807651  1.69373141]
 [1.56312409 2.66168747]]


In [ ]:
#outra forma de gerar aleatórios é pelas sementes
#as sementes permitem que eu gere uns números aleatórios e dps possa usá-los novamente
#eles ficam "guardados"
sem = np.random.default_rng(1)
ale3 = sem.random(5)
print(ale3) #não importa quantas vezes eu execute, será sempre os mesmos números
print("\n")
#gero aleatórios (que ficarão guardados) de tipo inteiro e valor máximo 10 em forma de matriz 3x2
ale4 = sem.integers(10, size=(3,2))
print(ale4)


[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]


[[8 4]
 [2 8]
 [2 4]]


In [ ]:
#removendo repetições numa array
vet = np.array([1,2,2,3,45,7,88,88,90])
vet = np.unique(vet)
print(vet)

[ 1  2  3  7 45 88 90]


In [ ]:
mt7 = np.array([ [1,2,3], [4,5,6], [7,8,9] ]) #matriz bidimensional
print(mt7)
print("\n")
print(mt7[0][2])
print("\n")
print(mt7.shape) #mostra o tamanho da matriz

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3


(3, 3)


In [ ]:
#mostra o maior valor da matriz k
print(mt7.max())
#mostra o menor valor da matriz k
print(mt7.min())
#mostra a soma dos valores da matriz k
print(mt7.sum())
#mostra a média dos valores da matriz k
print(mt7.mean())
#mostra a variância dos valores da matriz k
print(mt7.var())
#mostra a desvio padrão dos valores da matriz k
print(mt7.std())


9
1
45
5.0
6.666666666666667
2.581988897471611


In [ ]:
#funções aplicadas a cada um dos elementos
#raiz quadrada de cada elemento
k1 = np.array([1,2,3,4,5])
print(np.sqrt(k1))
#exponencial de cada elemento
print(np.exp(k1))
#logaritmo natural de cada elemento
print(np.log(k1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
m = np.array([2,3,5,4,1])
print(m[1]) #mostra o elemento da posiçao 1
print("\n")
print(m[0:2]) #mostra os elementos da posição 0 até a posição 2
print("\n")
print(m[1:]) #mostra os elementos da posição 1 até o final
print("\n")
print(m[-2:]) #mostra os dois últimos elementos
print("\n")
print(m[1:3]) #mostra os elementos da posição 1 até a posição 3
print("\n")

3


[2 3]


[3 5 4 1]


[4 1]


[3 5]




In [ ]:
l = np.array([[2,3,4],[34,2,11],[12,3,7]])
print(l)
print("\n")
#mostrando linhas com todas as colunas
l_linha1 = l[0, :]
print(l_linha1)
print("\n")
l_linha2 = l[1, :]
print(l_linha2)
print("\n")
l_linha3 = l[2,:]
print(l_linha3)
print("\n")
print("----------")
#mostrando colunas com todas as linhas
l_coluna1 = l[:,0]
print(l_coluna1)
print("\n")
l_coluna2 = l[:,1]
print(l_coluna2)
print("\n")
l_coluna3 = l[:,2]
print(l_coluna3)
print("\n")

[[ 2  3  4]
 [34  2 11]
 [12  3  7]]


[2 3 4]


[34  2 11]


[12  3  7]


----------
[ 2 34 12]


[3 2 3]


[ 4 11  7]




In [ ]:
#adição e multiplicação de matrizes
n = np.array([[1,2,3],[4,5,6]])
m = np.array([[2,3,4],[34,2,11]])
soma = n + m
print(soma)
print("\n")
mult = n * m
print(mult)
print("\n")
p = np.array([[2,3,4],[12,3,5],[6,73,2]])
o = np.array([1,2,3])
print(p + o)

[[ 3  5  7]
 [38  7 17]]


[[  2   6  12]
 [136  10  66]]


[[ 3  5  7]
 [13  5  8]
 [ 7 75  5]]


In [ ]:
trans = np.arange(15).reshape(3,5) #crio uma matriz com valor máximo < 15 com 3 linhas e 5 colunas
print(trans)
print("\n")
print(trans.T) #transposta

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#expressões lógicas
mat = np.random.randn(3,3)
print(mat)
print("\n")
x = mat > 0
print(x)
print("\n")
z = np.where(mat > 0,1,-1)
print(z)


[[ 1.70148889  1.91084288 -0.20282384]
 [-1.91369409 -0.94405778 -1.0521732 ]
 [ 0.84545819 -0.02871812  2.27741715]]


[[ True  True False]
 [False False False]
 [ True False  True]]


[[ 1  1 -1]
 [-1 -1 -1]
 [ 1 -1  1]]
